MySQL:
  enabled: false
  host: "127.0.0.1"
  port: 3306
  database: "mauth"
  user: "root"
  password: "root"

discord:
  bot-token: ""
  guild-id: ""
  role-id: ""
  playing: ""
  emoji: "✅"

messages:
  reloaded: "&7[&#a4ff67&l⚠&7] &fThe plugin has been reloaded."
  no-permission: "&7[&#a4ff67&l⚠&7] &fYou don't have permission to do this."
  command-for-player: "&7[&#a4ff67&l⚠&7] &fThis command is for players."
  account-not-linked: |
    &7[&#a4ff67&l⚠&7] &fPlease link your discord account with the command &7/mauth set <account_id>&f.
    &7[&#a4ff67&l⚠&7] &fTo log in you need to be on the servers with our bot.
  invalid-account: "&7[&#a4ff67&l⚠&7] &fThis is not your discord account ID."
  pm-is-closed: "&7[&#a4ff67&l⚠&7] &fYour PM is closed or you are not on the discord servers with our bot. The bot cannot write to you."
  confirm-message-sent: "&7[&#a4ff67&l✉&7] &fA confirmation message has been sent to you via PM."
  success-auth: "&7[&#a4ff67&l✉&7] &fYou have successfully logged in!"
  success-account-unlinked: "&7[&#a4ff67&l✉&7] &fYou have successfully unlinked your account!"
  account-already-linked: "&7[&#a4ff67&l✉&7] &fYou have already linked your account! To unlink it, type /mauth del"
  account-limit-per-ip: "&&7[#a4ff67&l⚠&7] &fYou cannot authorize more than one account from the same IP."
  account-busy: "&7[&#a4ff67&l⚠&7] &fThis discord is already linked to another player."
  player-account: "&7[&#a4ff67&l✉&7] &f{player} Discord: {id}."
  player-account-not-linked: "&7[&#a4ff67&l⚠&7] &fThe player has not linked his account."
  player-account-by-id: "&7[&#a4ff67&l✉&7] &f{id} Player: {player}."
  player-account-not-linked-by-id: "&7[&#a4ff67&l⚠&7] &fA player with this ID was not found."
  whitelisted: "&7[&#a4ff67&l✉&7] &fYou have added {ip} to the whitelist."
  unwhitelisted: "&7[&#a4ff67&l✉&7] &fYou have removed {ip} from the whitelist."
  help: |
    &7[&#a4ff67&l?&7] &f&lPlugin help:
    &7/mauth set <account_id> &f- Link your discord account.
    &7/mauth del &f- Unlink your discord account.
    &7/mauth get <player> &f- Get the player's discord.
    &7/mauth getById <account_id> &f- Get a player by discord ID.
    &7/mauth addwl <ip> &f- Allow registering more than 1 account.
    &7/mauth remwl <ip> &f- Again prohibit registering more than 1 account.

titles:
  account-not-linked-title: "&f&l» &#a4ff67&lM&#7fff95&lA&#60ffbd&lu&#55ffde&lt&#67fff6&lh &f&l«"
  account-not-linked-subtitle: "&fLink your discord account using &7/mauth set <account_id>"
  confirm-join-title: "&f&l» &#a4ff67&lM&#7fff95&lA&#60ffbd&lu&#55ffde&lt&#67fff6&lh &f&l«"
  confirm-join-subtitle: "&fPlease confirm your login."

embeds:
  confirm-unlink-desc: "To confirm **unlinking** your account, click on the checkmark."
  confirm-account-desc: "To confirm the **linking** of your account, click on the checkmark."
  confirm-join-desc: "To confirm **login** to the server, click on the checkmark."